version: 2.1

jobs:
  test:
    docker: # run the steps with Docker
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install node_modules
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
  build:
    docker: # run the steps with Docker
      - image: circleci/node:8
    steps:
      - run:
          name: Build
          command: yarn build
  deploy:
    docker: # run the steps with Docker
      - image: circleci/node:8
    steps:
      - run:
          name: Deploy
          command: yarn deploy
  sync_contentful:
    docker: # run the steps with Docker
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: Contentful Export
          command: yarn contentful-export
      - run:
          name: Contentful Import
          command: yarn contentful-import
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build
      - trigger_sync_contentful:
          type: approval
      - sync_contentful:
          requires:
            - trigger_sync_contentful
