workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build:
          docker: # run the steps with Docker
            - image: circleci/node:8
          steps:
            - checkout
            - restore_cache:
                key: dependency-cache-{{ checksum "package.json" }}
            - run:
                name: Install node_modules
                command: yarn
            - run:
                name: Build
                command: yarn build
            - save_cache:
                key: dependency-cache-{{ checksum "package.json" }}
                paths:
                  - ./node_modules
      - deploy:
          docker: # run the steps with Docker
            - image: circleci/node:8
          requires:
            - build
          steps:
            - run:
                name: Deploy
                command: yarn deploy
